### PR TITLE
Testing components

### PR DESCRIPTION
**Pull request by Ney2**
This is a PR for testing all of the components.
1. Add unit testing for calculate and operate files
2. Add snapshots testing for all the components

### CODE REVIEW

**Review by aimemalaika — CHANGES_REQUESTED** [review]
Hi @Ney2 & @eudondian,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

the-simpsons-homer-simpson

## To Highlight 🎉

- No linter errors. ✔️
- GitHub flow is followed. ✔️
- Professional README file. ✔️
- PR has a good title and summary. ✔️

 ## Required Changes ♻️

- [ ] Kindly make sure to have equal contributions in a group project @eudondian has only contributed on the readme file. 
- [ ] @eudondian Kindly write some unit tests to contribute to the project

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Ney2** [comment]
@aimemalaika ,
Thank you for your feedback, but I think there is a misunderstanding. @eudondian  has contributed to the test case all the commits after mine is hers.

**Comment by aimemalaika** [comment]
Hello @Ney2 

Kindly check this screenshots bellow

Screen Shot 2022-08-18 at 17 21 34

Screen Shot 2022-08-18 at 17 24 15

**Comment by aimemalaika** [comment]
Hello @Ney2 ,

After checking the git log, i  have found her commits. sorry for the mistake. you can go ahead and request another review. 
Screen Shot 2022-08-18 at 17 27 15

**Comment by Ney2** [comment]
@aimemalaika 
I really thank you for your information.

**Comment by aimemalaika** [comment]
@Ney2 you are welcome

**Pull request merged**
